return {
	PlaceObj('ModItemCharacterEffectCompositeDef', {
		'Group', "System",
		'Id', "SuitUp",
		'SortKey', 100,
		'object_class', "CharacterEffect",
		'msg_reactions', {
			PlaceObj('MsgActorReactionEffects', {
				Effects = {
					PlaceObj('ConditionalEffect', {
						'Conditions', {
							PlaceObj('SectorIsInConflict', {
								param_bindings = false,
							}),
						},
						'Effects', {
							PlaceObj('UnitApplyAppearance', {
								Appearance = "Kalyna_battlemode",
								TargetUnit = "Kalyna",
								param_bindings = false,
							}),
							PlaceObj('UnitApplyAppearance', {
								Appearance = "Ivan_battlemode",
								TargetUnit = "Ivan",
								param_bindings = false,
							}),
							PlaceObj('UnitApplyAppearance', {
								Appearance = "Mouse_battlemode",
								TargetUnit = "Mouse",
								param_bindings = false,
							}),
							PlaceObj('UnitApplyAppearance', {
								Appearance = "Nails_battlemode",
								TargetUnit = "Nails",
								param_bindings = false,
							}),
							PlaceObj('UnitApplyAppearance', {
								Appearance = "Thor_battlemode",
								TargetUnit = "Thor",
								param_bindings = false,
							}),
							PlaceObj('UnitApplyAppearance', {
								Appearance = "Barry_battlemode",
								TargetUnit = "Barry",
								param_bindings = false,
							}),
							PlaceObj('UnitApplyAppearance', {
								Appearance = "Buns_battlemode",
								TargetUnit = "Buns",
								param_bindings = false,
							}),
							PlaceObj('UnitApplyAppearance', {
								Appearance = "Fox_battlemode",
								TargetUnit = "Fox",
								param_bindings = false,
							}),
							PlaceObj('UnitApplyAppearance', {
								Appearance = "Grunty_battlemode",
								TargetUnit = "Grunty",
								param_bindings = false,
							}),
							PlaceObj('UnitApplyAppearance', {
								Appearance = "Hitman_battlemode",
								TargetUnit = "Hitman",
								param_bindings = false,
							}),
							PlaceObj('UnitApplyAppearance', {
								Appearance = "Ice_battlemode",
								TargetUnit = "Ice",
								param_bindings = false,
							}),
							PlaceObj('UnitApplyAppearance', {
								Appearance = "Magic_battlemode",
								TargetUnit = "Magic",
								param_bindings = false,
							}),
							PlaceObj('UnitApplyAppearance', {
								Appearance = "MD_battlemode",
								TargetUnit = "MD",
								param_bindings = false,
							}),
							PlaceObj('UnitApplyAppearance', {
								Appearance = "Meltdown_battlemode",
								TargetUnit = "Meltdown",
								param_bindings = false,
							}),
							PlaceObj('UnitApplyAppearance', {
								Appearance = "Reaper_battlemode",
								TargetUnit = "Reaper",
								param_bindings = false,
							}),
							PlaceObj('UnitApplyAppearance', {
								Appearance = "Sidney_battlemode",
								TargetUnit = "Sidney",
								param_bindings = false,
							}),
							PlaceObj('UnitApplyAppearance', {
								Appearance = "Scully_battlemode",
								TargetUnit = "Scully",
								param_bindings = false,
							}),
							PlaceObj('UnitApplyAppearance', {
								Appearance = "Tex_battlemode",
								TargetUnit = "Tex",
								param_bindings = false,
							}),
						},
					}),
				},
				Event = "ExplorationStart",
				Handler = function (self)
					ExecReactionEffects(self, 1, "ExplorationStart", nil, self)
				end,
				param_bindings = false,
			}),
			PlaceObj('MsgActorReactionEffects', {
				Effects = {
					PlaceObj('ConditionalEffect', {
						'Conditions', {
							PlaceObj('SectorIsInConflict', {
								param_bindings = false,
							}),
						},
						'Effects', {
							PlaceObj('UnitApplyAppearance', {
								Appearance = "Kalyna_battlemode",
								TargetUnit = "Kalyna",
								param_bindings = false,
							}),
							PlaceObj('UnitApplyAppearance', {
								Appearance = "Ivan_battlemode",
								TargetUnit = "Ivan",
								param_bindings = false,
							}),
							PlaceObj('UnitApplyAppearance', {
								Appearance = "Mouse_battlemode",
								TargetUnit = "Mouse",
								param_bindings = false,
							}),
							PlaceObj('UnitApplyAppearance', {
								Appearance = "Nails_battlemode",
								TargetUnit = "Nails",
								param_bindings = false,
							}),
							PlaceObj('UnitApplyAppearance', {
								Appearance = "Thor_battlemode",
								TargetUnit = "Thor",
								param_bindings = false,
							}),
							PlaceObj('UnitApplyAppearance', {
								Appearance = "Barry_battlemode",
								TargetUnit = "Barry",
								param_bindings = false,
							}),
							PlaceObj('UnitApplyAppearance', {
								Appearance = "Buns_battlemode",
								TargetUnit = "Buns",
								param_bindings = false,
							}),
							PlaceObj('UnitApplyAppearance', {
								Appearance = "Fox_battlemode",
								TargetUnit = "Fox",
								param_bindings = false,
							}),
							PlaceObj('UnitApplyAppearance', {
								Appearance = "Grunty_battlemode",
								TargetUnit = "Grunty",
								param_bindings = false,
							}),
							PlaceObj('UnitApplyAppearance', {
								Appearance = "Hitman_battlemode",
								TargetUnit = "Hitman",
								param_bindings = false,
							}),
							PlaceObj('UnitApplyAppearance', {
								Appearance = "Ice_battlemode",
								TargetUnit = "Ice",
								param_bindings = false,
							}),
							PlaceObj('UnitApplyAppearance', {
								Appearance = "Magic_battlemode",
								TargetUnit = "Magic",
								param_bindings = false,
							}),
							PlaceObj('UnitApplyAppearance', {
								Appearance = "MD_battlemode",
								TargetUnit = "MD",
								param_bindings = false,
							}),
							PlaceObj('UnitApplyAppearance', {
								Appearance = "Meltdown_battlemode",
								TargetUnit = "Meltdown",
								param_bindings = false,
							}),
							PlaceObj('UnitApplyAppearance', {
								Appearance = "Reaper_battlemode",
								TargetUnit = "Reaper",
								param_bindings = false,
							}),
							PlaceObj('UnitApplyAppearance', {
								Appearance = "Sidney_battlemode",
								TargetUnit = "Sidney",
								param_bindings = false,
							}),
							PlaceObj('UnitApplyAppearance', {
								Appearance = "Scully_battlemode",
								TargetUnit = "Scully",
								param_bindings = false,
							}),
							PlaceObj('UnitApplyAppearance', {
								Appearance = "Tex_battlemode",
								TargetUnit = "Tex",
								param_bindings = false,
							}),
						},
					}),
				},
				Event = "CombatStart",
				Handler = function (self, dynamic_data)
					ExecReactionEffects(self, 2, "CombatStart", nil, self, dynamic_data)
				end,
				param_bindings = false,
			}),
			PlaceObj('MsgActorReactionEffects', {
				Effects = {
					PlaceObj('ConditionalEffect', {
						'Conditions', {
							PlaceObj('SectorIsInConflict', {
								param_bindings = false,
							}),
						},
						'Effects', {
							PlaceObj('UnitApplyAppearance', {
								Appearance = "Kalyna_battlemode",
								TargetUnit = "Kalyna",
								param_bindings = false,
							}),
							PlaceObj('UnitApplyAppearance', {
								Appearance = "Ivan_battlemode",
								TargetUnit = "Ivan",
								param_bindings = false,
							}),
							PlaceObj('UnitApplyAppearance', {
								Appearance = "Mouse_battlemode",
								TargetUnit = "Mouse",
								param_bindings = false,
							}),
							PlaceObj('UnitApplyAppearance', {
								Appearance = "Nails_battlemode",
								TargetUnit = "Nails",
								param_bindings = false,
							}),
							PlaceObj('UnitApplyAppearance', {
								Appearance = "Thor_battlemode",
								TargetUnit = "Thor",
								param_bindings = false,
							}),
							PlaceObj('UnitApplyAppearance', {
								Appearance = "Barry_battlemode",
								TargetUnit = "Barry",
								param_bindings = false,
							}),
							PlaceObj('UnitApplyAppearance', {
								Appearance = "Buns_battlemode",
								TargetUnit = "Buns",
								param_bindings = false,
							}),
							PlaceObj('UnitApplyAppearance', {
								Appearance = "Fox_battlemode",
								TargetUnit = "Fox",
								param_bindings = false,
							}),
							PlaceObj('UnitApplyAppearance', {
								Appearance = "Grunty_battlemode",
								TargetUnit = "Grunty",
								param_bindings = false,
							}),
							PlaceObj('UnitApplyAppearance', {
								Appearance = "Hitman_battlemode",
								TargetUnit = "Hitman",
								param_bindings = false,
							}),
							PlaceObj('UnitApplyAppearance', {
								Appearance = "Ice_battlemode",
								TargetUnit = "Ice",
								param_bindings = false,
							}),
							PlaceObj('UnitApplyAppearance', {
								Appearance = "Magic_battlemode",
								TargetUnit = "Magic",
								param_bindings = false,
							}),
							PlaceObj('UnitApplyAppearance', {
								Appearance = "MD_battlemode",
								TargetUnit = "MD",
								param_bindings = false,
							}),
							PlaceObj('UnitApplyAppearance', {
								Appearance = "Meltdown_battlemode",
								TargetUnit = "Meltdown",
								param_bindings = false,
							}),
							PlaceObj('UnitApplyAppearance', {
								Appearance = "Reaper_battlemode",
								TargetUnit = "Reaper",
								param_bindings = false,
							}),
							PlaceObj('UnitApplyAppearance', {
								Appearance = "Sidney_battlemode",
								TargetUnit = "Sidney",
								param_bindings = false,
							}),
							PlaceObj('UnitApplyAppearance', {
								Appearance = "Scully_battlemode",
								TargetUnit = "Scully",
								param_bindings = false,
							}),
							PlaceObj('UnitApplyAppearance', {
								Appearance = "Tex_battlemode",
								TargetUnit = "Tex",
								param_bindings = false,
							}),
						},
					}),
				},
				Event = "TurnStart",
				Handler = function (self, team)
					ExecReactionEffects(self, 3, "TurnStart", nil, self, team)
				end,
				param_bindings = false,
			}),
			PlaceObj('MsgActorReactionEffects', {
				Effects = {
					PlaceObj('ConditionalEffect', {
						'Conditions', {
							PlaceObj('SectorIsInConflict', {
								param_bindings = false,
							}),
						},
						'Effects', {
							PlaceObj('UnitApplyAppearance', {
								Appearance = "Kalyna_battlemode",
								TargetUnit = "Kalyna",
								param_bindings = false,
							}),
							PlaceObj('UnitApplyAppearance', {
								Appearance = "Ivan_battlemode",
								TargetUnit = "Ivan",
								param_bindings = false,
							}),
							PlaceObj('UnitApplyAppearance', {
								Appearance = "Mouse_battlemode",
								TargetUnit = "Mouse",
								param_bindings = false,
							}),
							PlaceObj('UnitApplyAppearance', {
								Appearance = "Nails_battlemode",
								TargetUnit = "Nails",
								param_bindings = false,
							}),
							PlaceObj('UnitApplyAppearance', {
								Appearance = "Thor_battlemode",
								TargetUnit = "Thor",
								param_bindings = false,
							}),
							PlaceObj('UnitApplyAppearance', {
								Appearance = "Barry_battlemode",
								TargetUnit = "Barry",
								param_bindings = false,
							}),
							PlaceObj('UnitApplyAppearance', {
								Appearance = "Buns_battlemode",
								TargetUnit = "Buns",
								param_bindings = false,
							}),
							PlaceObj('UnitApplyAppearance', {
								Appearance = "Fox_battlemode",
								TargetUnit = "Fox",
								param_bindings = false,
							}),
							PlaceObj('UnitApplyAppearance', {
								Appearance = "Grunty_battlemode",
								TargetUnit = "Grunty",
								param_bindings = false,
							}),
							PlaceObj('UnitApplyAppearance', {
								Appearance = "Hitman_battlemode",
								TargetUnit = "Hitman",
								param_bindings = false,
							}),
							PlaceObj('UnitApplyAppearance', {
								Appearance = "Ice_battlemode",
								TargetUnit = "Ice",
								param_bindings = false,
							}),
							PlaceObj('UnitApplyAppearance', {
								Appearance = "Magic_battlemode",
								TargetUnit = "Magic",
								param_bindings = false,
							}),
							PlaceObj('UnitApplyAppearance', {
								Appearance = "MD_battlemode",
								TargetUnit = "MD",
								param_bindings = false,
							}),
							PlaceObj('UnitApplyAppearance', {
								Appearance = "Meltdown_battlemode",
								TargetUnit = "Meltdown",
								param_bindings = false,
							}),
							PlaceObj('UnitApplyAppearance', {
								Appearance = "Reaper_battlemode",
								TargetUnit = "Reaper",
								param_bindings = false,
							}),
							PlaceObj('UnitApplyAppearance', {
								Appearance = "Sidney_battlemode",
								TargetUnit = "Sidney",
								param_bindings = false,
							}),
							PlaceObj('UnitApplyAppearance', {
								Appearance = "Scully_battlemode",
								TargetUnit = "Scully",
								param_bindings = false,
							}),
							PlaceObj('UnitApplyAppearance', {
								Appearance = "Tex_battlemode",
								TargetUnit = "Tex",
								param_bindings = false,
							}),
						},
					}),
				},
				Event = "InventoryChange",
				Handler = function (self, obj)
					ExecReactionEffects(self, 4, "InventoryChange", nil, self, obj)
				end,
				param_bindings = false,
			}),
			PlaceObj('MsgActorReactionEffects', {
				Effects = {
					PlaceObj('ConditionalEffect', {
						'Conditions', {
							PlaceObj('SectorIsInConflict', {
								param_bindings = false,
							}),
						},
						'Effects', {
							PlaceObj('UnitApplyAppearance', {
								Appearance = "Kalyna_battlemode",
								TargetUnit = "Kalyna",
								param_bindings = false,
							}),
							PlaceObj('UnitApplyAppearance', {
								Appearance = "Ivan_battlemode",
								TargetUnit = "Ivan",
								param_bindings = false,
							}),
							PlaceObj('UnitApplyAppearance', {
								Appearance = "Mouse_battlemode",
								TargetUnit = "Mouse",
								param_bindings = false,
							}),
							PlaceObj('UnitApplyAppearance', {
								Appearance = "Nails_battlemode",
								TargetUnit = "Nails",
								param_bindings = false,
							}),
							PlaceObj('UnitApplyAppearance', {
								Appearance = "Thor_battlemode",
								TargetUnit = "Thor",
								param_bindings = false,
							}),
							PlaceObj('UnitApplyAppearance', {
								Appearance = "Barry_battlemode",
								TargetUnit = "Barry",
								param_bindings = false,
							}),
							PlaceObj('UnitApplyAppearance', {
								Appearance = "Buns_battlemode",
								TargetUnit = "Buns",
								param_bindings = false,
							}),
							PlaceObj('UnitApplyAppearance', {
								Appearance = "Fox_battlemode",
								TargetUnit = "Fox",
								param_bindings = false,
							}),
							PlaceObj('UnitApplyAppearance', {
								Appearance = "Grunty_battlemode",
								TargetUnit = "Grunty",
								param_bindings = false,
							}),
							PlaceObj('UnitApplyAppearance', {
								Appearance = "Hitman_battlemode",
								TargetUnit = "Hitman",
								param_bindings = false,
							}),
							PlaceObj('UnitApplyAppearance', {
								Appearance = "Ice_battlemode",
								TargetUnit = "Ice",
								param_bindings = false,
							}),
							PlaceObj('UnitApplyAppearance', {
								Appearance = "Magic_battlemode",
								TargetUnit = "Magic",
								param_bindings = false,
							}),
							PlaceObj('UnitApplyAppearance', {
								Appearance = "MD_battlemode",
								TargetUnit = "MD",
								param_bindings = false,
							}),
							PlaceObj('UnitApplyAppearance', {
								Appearance = "Meltdown_battlemode",
								TargetUnit = "Meltdown",
								param_bindings = false,
							}),
							PlaceObj('UnitApplyAppearance', {
								Appearance = "Reaper_battlemode",
								TargetUnit = "Reaper",
								param_bindings = false,
							}),
							PlaceObj('UnitApplyAppearance', {
								Appearance = "Sidney_battlemode",
								TargetUnit = "Sidney",
								param_bindings = false,
							}),
							PlaceObj('UnitApplyAppearance', {
								Appearance = "Scully_battlemode",
								TargetUnit = "Scully",
								param_bindings = false,
							}),
							PlaceObj('UnitApplyAppearance', {
								Appearance = "Tex_battlemode",
								TargetUnit = "Tex",
								param_bindings = false,
							}),
						},
					}),
				},
				Event = "DamageTaken",
				Handler = function (self, attacker, target, dmg, hit_descr)
					ExecReactionEffects(self, 5, "DamageTaken", nil, self, attacker, target, dmg, hit_descr)
				end,
				param_bindings = false,
			}),
			PlaceObj('MsgActorReactionEffects', {
				Effects = {
					PlaceObj('ConditionalEffect', {
						'Conditions', {
							PlaceObj('SectorIsInConflict', {
								param_bindings = false,
							}),
						},
						'Effects', {
							PlaceObj('UnitApplyAppearance', {
								Appearance = "Kalyna_battlemode",
								TargetUnit = "Kalyna",
								param_bindings = false,
							}),
							PlaceObj('UnitApplyAppearance', {
								Appearance = "Ivan_battlemode",
								TargetUnit = "Ivan",
								param_bindings = false,
							}),
							PlaceObj('UnitApplyAppearance', {
								Appearance = "Mouse_battlemode",
								TargetUnit = "Mouse",
								param_bindings = false,
							}),
							PlaceObj('UnitApplyAppearance', {
								Appearance = "Nails_battlemode",
								TargetUnit = "Nails",
								param_bindings = false,
							}),
							PlaceObj('UnitApplyAppearance', {
								Appearance = "Thor_battlemode",
								TargetUnit = "Thor",
								param_bindings = false,
							}),
							PlaceObj('UnitApplyAppearance', {
								Appearance = "Barry_battlemode",
								TargetUnit = "Barry",
								param_bindings = false,
							}),
							PlaceObj('UnitApplyAppearance', {
								Appearance = "Buns_battlemode",
								TargetUnit = "Buns",
								param_bindings = false,
							}),
							PlaceObj('UnitApplyAppearance', {
								Appearance = "Fox_battlemode",
								TargetUnit = "Fox",
								param_bindings = false,
							}),
							PlaceObj('UnitApplyAppearance', {
								Appearance = "Grunty_battlemode",
								TargetUnit = "Grunty",
								param_bindings = false,
							}),
							PlaceObj('UnitApplyAppearance', {
								Appearance = "Hitman_battlemode",
								TargetUnit = "Hitman",
								param_bindings = false,
							}),
							PlaceObj('UnitApplyAppearance', {
								Appearance = "Ice_battlemode",
								TargetUnit = "Ice",
								param_bindings = false,
							}),
							PlaceObj('UnitApplyAppearance', {
								Appearance = "Magic_battlemode",
								TargetUnit = "Magic",
								param_bindings = false,
							}),
							PlaceObj('UnitApplyAppearance', {
								Appearance = "MD_battlemode",
								TargetUnit = "MD",
								param_bindings = false,
							}),
							PlaceObj('UnitApplyAppearance', {
								Appearance = "Meltdown_battlemode",
								TargetUnit = "Meltdown",
								param_bindings = false,
							}),
							PlaceObj('UnitApplyAppearance', {
								Appearance = "Reaper_battlemode",
								TargetUnit = "Reaper",
								param_bindings = false,
							}),
							PlaceObj('UnitApplyAppearance', {
								Appearance = "Sidney_battlemode",
								TargetUnit = "Sidney",
								param_bindings = false,
							}),
							PlaceObj('UnitApplyAppearance', {
								Appearance = "Scully_battlemode",
								TargetUnit = "Scully",
								param_bindings = false,
							}),
							PlaceObj('UnitApplyAppearance', {
								Appearance = "Tex_battlemode",
								TargetUnit = "Tex",
								param_bindings = false,
							}),
						},
					}),
				},
				Event = "StatusEffectAdded",
				Handler = function (self, obj, id, stacks)
					ExecReactionEffects(self, 6, "StatusEffectAdded", nil, self, obj, id, stacks)
				end,
				param_bindings = false,
			}),
			PlaceObj('MsgActorReactionEffects', {
				Effects = {
					PlaceObj('ConditionalEffect', {
						'Conditions', {
							PlaceObj('SectorIsInConflict', {
								param_bindings = false,
							}),
						},
						'Effects', {
							PlaceObj('UnitApplyAppearance', {
								Appearance = "Kalyna_battlemode",
								TargetUnit = "Kalyna",
								param_bindings = false,
							}),
							PlaceObj('UnitApplyAppearance', {
								Appearance = "Ivan_battlemode",
								TargetUnit = "Ivan",
								param_bindings = false,
							}),
							PlaceObj('UnitApplyAppearance', {
								Appearance = "Mouse_battlemode",
								TargetUnit = "Mouse",
								param_bindings = false,
							}),
							PlaceObj('UnitApplyAppearance', {
								Appearance = "Nails_battlemode",
								TargetUnit = "Nails",
								param_bindings = false,
							}),
							PlaceObj('UnitApplyAppearance', {
								Appearance = "Thor_battlemode",
								TargetUnit = "Thor",
								param_bindings = false,
							}),
							PlaceObj('UnitApplyAppearance', {
								Appearance = "Barry_battlemode",
								TargetUnit = "Barry",
								param_bindings = false,
							}),
							PlaceObj('UnitApplyAppearance', {
								Appearance = "Buns_battlemode",
								TargetUnit = "Buns",
								param_bindings = false,
							}),
							PlaceObj('UnitApplyAppearance', {
								Appearance = "Fox_battlemode",
								TargetUnit = "Fox",
								param_bindings = false,
							}),
							PlaceObj('UnitApplyAppearance', {
								Appearance = "Grunty_battlemode",
								TargetUnit = "Grunty",
								param_bindings = false,
							}),
							PlaceObj('UnitApplyAppearance', {
								Appearance = "Hitman_battlemode",
								TargetUnit = "Hitman",
								param_bindings = false,
							}),
							PlaceObj('UnitApplyAppearance', {
								Appearance = "Ice_battlemode",
								TargetUnit = "Ice",
								param_bindings = false,
							}),
							PlaceObj('UnitApplyAppearance', {
								Appearance = "Magic_battlemode",
								TargetUnit = "Magic",
								param_bindings = false,
							}),
							PlaceObj('UnitApplyAppearance', {
								Appearance = "MD_battlemode",
								TargetUnit = "MD",
								param_bindings = false,
							}),
							PlaceObj('UnitApplyAppearance', {
								Appearance = "Meltdown_battlemode",
								TargetUnit = "Meltdown",
								param_bindings = false,
							}),
							PlaceObj('UnitApplyAppearance', {
								Appearance = "Reaper_battlemode",
								TargetUnit = "Reaper",
								param_bindings = false,
							}),
							PlaceObj('UnitApplyAppearance', {
								Appearance = "Sidney_battlemode",
								TargetUnit = "Sidney",
								param_bindings = false,
							}),
							PlaceObj('UnitApplyAppearance', {
								Appearance = "Scully_battlemode",
								TargetUnit = "Scully",
								param_bindings = false,
							}),
							PlaceObj('UnitApplyAppearance', {
								Appearance = "Tex_battlemode",
								TargetUnit = "Tex",
								param_bindings = false,
							}),
						},
					}),
				},
				Event = "StatusEffectRemoved",
				Handler = function (self, obj, id, stacks, reason)
					ExecReactionEffects(self, 7, "StatusEffectRemoved", nil, self, obj, id, stacks, reason)
				end,
				param_bindings = false,
			}),
		},
		'unit_reactions', {},
		'Conditions', {},
		'Modifiers', {},
		'Description', T(835606447630, --[[ModItemCharacterEffectCompositeDef SuitUp Description]] "Suit up."),
	}),
	PlaceObj('ModItemCode', {
		'name', "SuitUp",
		'CodeFileName', "Code/SuitUp.lua",
	}),
	PlaceObj('ModItemFolder', {
		'name', "Appearance Presets",
	}, {
		PlaceObj('ModItemAppearancePreset', {
			Armor = "EquipmentMale_FlackVest",
			ArmorColor = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(2, 9, 0, 255),
				'EditableColor2', RGBA(17, 17, 17, 255),
				'EditableColor3', RGBA(2, 9, 0, 255),
			}),
			Body = "Faction_GrandChien_Top",
			BodyColor = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(250, 93, 50, 255),
				'EditableColor2', RGBA(88, 92, 68, 255),
				'EditableColor3', RGBA(88, 92, 68, 255),
			}),
			Chest = "",
			ChestColor = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(0, 0, 0, 255),
				'EditableColor2', RGBA(0, 0, 0, 255),
				'EditableColor3', RGBA(0, 0, 0, 255),
			}),
			Hair = "EquipmentBarry_Hair",
			HairColor = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(21, 20, 19, 255),
				'EditableMetallic1', -47,
				'EditableColor2', RGBA(25, 24, 23, 255),
				'EditableMetallic2', -128,
				'EditableRoughness3', -128,
			}),
			HairParam1 = 55,
			HairParam2 = 20,
			HairParam3 = 107,
			Hat2AttachOffsetAngle = -18000,
			Hat2Color = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(0, 0, 0, 255),
				'EditableColor2', RGBA(0, 0, 0, 255),
				'EditableColor3', RGBA(0, 0, 0, 255),
			}),
			HatColor = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(0, 0, 0, 255),
				'EditableColor2', RGBA(0, 0, 0, 255),
				'EditableColor3', RGBA(0, 0, 0, 255),
			}),
			Head = "Head_Barry",
			HeadColor = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(0, 0, 0, 255),
				'EditableColor2', RGBA(0, 0, 0, 255),
				'EditableColor3', RGBA(0, 0, 0, 255),
			}),
			Hip = "Faction_Acc_Stormer",
			HipColor = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(30, 15, 8, 255),
				'EditableColor2', RGBA(17, 17, 17, 255),
				'EditableColor3', RGBA(0, 72, 130, 255),
			}),
			Pants = "EquipmentBarry_Bottom",
			PantsColor = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(0, 0, 0, 255),
				'EditableColor2', RGBA(0, 0, 0, 255),
				'EditableColor3', RGBA(0, 0, 0, 255),
			}),
			Shirt = "",
			ShirtColor = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(0, 0, 0, 255),
				'EditableColor2', RGBA(0, 0, 0, 255),
				'EditableColor3', RGBA(0, 0, 0, 255),
			}),
			group = "Mercs",
			id = "Barry_battlemode",
		}),
		PlaceObj('ModItemAppearancePreset', {
			ArmorColor = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(0, 0, 0, 255),
				'EditableColor2', RGBA(0, 0, 0, 255),
				'EditableColor3', RGBA(0, 0, 0, 255),
			}),
			Body = "EquipmentCorazon_Top_BattleMod",
			BodyColor = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(92, 48, 31, 255),
				'EditableColor2', RGBA(88, 92, 68, 255),
				'EditableColor3', RGBA(88, 92, 68, 255),
			}),
			ChestColor = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(0, 0, 0, 255),
				'EditableColor2', RGBA(0, 0, 0, 255),
				'EditableColor3', RGBA(0, 0, 0, 255),
			}),
			Hair = "EquipmentBuns_Hair",
			HairColor = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(246, 158, 95, 255),
				'EditableColor2', RGBA(255, 213, 113, 255),
				'EditableColor3', RGBA(0, 0, 0, 255),
				'EditableRoughness3', -15,
			}),
			HairParam2 = 22,
			HairParam3 = 44,
			Hat = "",
			Hat2 = "EquipmentCorazon_Glasses_BattleMod",
			Hat2Color = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(11, 11, 11, 255),
				'EditableColor2', RGBA(230, 222, 202, 255),
				'EditableColor3', RGBA(230, 222, 202, 255),
			}),
			HatColor = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(0, 0, 0, 255),
				'EditableColor2', RGBA(0, 0, 0, 255),
				'EditableColor3', RGBA(0, 0, 0, 255),
			}),
			Head = "Head_Buns",
			HeadColor = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(0, 0, 0, 255),
				'EditableColor2', RGBA(0, 0, 0, 255),
				'EditableColor3', RGBA(0, 0, 0, 255),
			}),
			Hip = "",
			HipColor = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(0, 0, 0, 255),
				'EditableColor2', RGBA(0, 0, 0, 255),
				'EditableColor3', RGBA(0, 0, 0, 255),
			}),
			Pants = "EquipmentCorazon_Bottom_BattleMod",
			PantsColor = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(44, 46, 34, 255),
				'EditableColor2', RGBA(78, 72, 72, 255),
				'EditableColor3', RGBA(78, 72, 72, 255),
			}),
			ShirtColor = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(171, 141, 71, 255),
				'EditableColor2', RGBA(0, 0, 0, 255),
				'EditableColor3', RGBA(0, 0, 0, 255),
			}),
			group = "Mercs",
			id = "Buns_battlemode",
		}),
		PlaceObj('ModItemAppearancePreset', {
			ArmorColor = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(0, 0, 0, 255),
				'EditableColor2', RGBA(0, 0, 0, 255),
				'EditableColor3', RGBA(0, 0, 0, 255),
			}),
			Body = "EquipmentIMPTrooper_Top",
			BodyColor = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(240, 120, 60, 255),
				'EditableColor2', RGBA(17, 17, 17, 255),
				'EditableColor3', RGBA(62, 48, 15, 255),
			}),
			ChestColor = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(0, 0, 0, 255),
				'EditableColor2', RGBA(0, 0, 0, 255),
				'EditableColor3', RGBA(0, 0, 0, 255),
			}),
			Hair = "EquipmentFox_Hair",
			HairColor = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(19, 11, 7, 255),
				'EditableRoughness1', 10,
				'EditableMetallic1', -70,
				'EditableColor2', RGBA(29, 22, 18, 255),
				'EditableRoughness2', -44,
				'EditableMetallic2', -128,
				'EditableColor3', RGBA(255, 255, 255, 255),
				'EditableRoughness3', -25,
				'EditableMetallic3', 127,
			}),
			HairParam1 = 61,
			HairParam2 = 16,
			Hat = "EquipmentFox_Glasses",
			Hat2Color = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(0, 0, 0, 255),
				'EditableColor2', RGBA(0, 0, 0, 255),
				'EditableColor3', RGBA(0, 0, 0, 255),
			}),
			HatColor = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(0, 0, 0, 255),
				'EditableColor2', RGBA(0, 0, 0, 255),
				'EditableColor3', RGBA(0, 0, 0, 255),
			}),
			Head = "Head_Fox",
			HeadColor = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(0, 0, 0, 255),
				'EditableColor2', RGBA(0, 0, 0, 255),
				'EditableColor3', RGBA(0, 0, 0, 255),
			}),
			HipColor = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(0, 0, 0, 255),
				'EditableColor2', RGBA(0, 0, 0, 255),
				'EditableColor3', RGBA(0, 0, 0, 255),
			}),
			Pants = "EquipmentFox_Bottom",
			PantsColor = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(0, 0, 0, 255),
				'EditableColor2', RGBA(0, 0, 0, 255),
				'EditableColor3', RGBA(0, 0, 0, 255),
			}),
			ShirtColor = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(0, 0, 0, 255),
				'EditableColor2', RGBA(0, 0, 0, 255),
				'EditableColor3', RGBA(0, 0, 0, 255),
			}),
			group = "Mercs",
			id = "Fox_battlemode",
		}),
		PlaceObj('ModItemAppearancePreset', {
			Armor = "EquipmentMale_InterceptorVest_02",
			ArmorColor = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(124, 130, 96, 255),
				'EditableColor2', RGBA(5, 5, 5, 255),
				'EditableColor3', RGBA(5, 5, 5, 255),
			}),
			Body = "EquipmentIMPFixer_Top",
			BodyColor = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(180, 90, 45, 255),
				'EditableColor2', RGBA(32, 32, 32, 255),
				'EditableColor3', RGBA(0, 0, 0, 255),
			}),
			ChestColor = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(0, 0, 0, 255),
				'EditableColor2', RGBA(0, 0, 0, 255),
				'EditableColor3', RGBA(0, 0, 0, 255),
			}),
			Hair = "EquipmentGrunty_Hair",
			HairColor = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(128, 88, 38, 255),
				'EditableRoughness1', 20,
				'EditableMetallic1', -119,
				'EditableColor2', RGBA(77, 36, 6, 255),
				'EditableMetallic2', -128,
				'EditableMetallic3', 127,
			}),
			HairParam1 = 34,
			HairParam3 = 104,
			Hat = "EquipmentGrunty_Glasses",
			Hat2Color = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(0, 0, 0, 255),
				'EditableColor2', RGBA(0, 0, 0, 255),
				'EditableColor3', RGBA(0, 0, 0, 255),
			}),
			HatColor = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(242, 177, 84, 255),
				'EditableColor2', RGBA(99, 32, 14, 255),
				'EditableColor3', RGBA(0, 0, 0, 255),
			}),
			Head = "Head_Grunty",
			HeadColor = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(0, 0, 0, 255),
				'EditableColor2', RGBA(0, 0, 0, 255),
				'EditableColor3', RGBA(0, 0, 0, 255),
			}),
			Hip = "Faction_Acc_Soldier",
			HipColor = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(17, 17, 17, 255),
				'EditableColor2', RGBA(5, 5, 5, 255),
				'EditableColor3', RGBA(17, 17, 17, 255),
			}),
			Pants = "EquipmentIMPGunny_Pants",
			PantsColor = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(21, 21, 21, 255),
				'EditableColor2', RGBA(5, 5, 5, 255),
				'EditableColor3', RGBA(5, 5, 5, 255),
			}),
			ShirtColor = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(0, 0, 0, 255),
				'EditableColor2', RGBA(0, 0, 0, 255),
				'EditableColor3', RGBA(0, 0, 0, 255),
			}),
			group = "Mercs",
			id = "Grunty_battlemode",
		}),
		PlaceObj('ModItemAppearancePreset', {
			ArmorColor = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(0, 0, 0, 255),
				'EditableColor2', RGBA(0, 0, 0, 255),
				'EditableColor3', RGBA(0, 0, 0, 255),
			}),
			Body = "EquipmentBiff_Top",
			BodyColor = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(130, 55, 25, 255),
				'EditableColor2', RGBA(60, 62, 54, 255),
				'EditableColor3', RGBA(100, 114, 118, 255),
			}),
			Chest = "Faction_RadioDevice_01",
			ChestColor = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(90, 45, 30, 255),
				'EditableColor2', RGBA(100, 114, 118, 255),
				'EditableColor3', RGBA(100, 114, 118, 255),
			}),
			Hair = "EquipmentHitman_Hair",
			HairColor = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(26, 23, 23, 255),
				'EditableRoughness1', 29,
				'EditableColor2', RGBA(51, 47, 45, 255),
				'EditableRoughness2', 33,
				'EditableMetallic2', -128,
				'EditableColor3', RGBA(33, 31, 30, 255),
				'EditableRoughness3', 36,
				'EditableMetallic3', 127,
			}),
			HairParam1 = 90,
			HairParam3 = 131,
			Hat = "EquipmentHitman_Glasses",
			Hat2Color = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(0, 0, 0, 255),
				'EditableColor2', RGBA(0, 0, 0, 255),
				'EditableColor3', RGBA(0, 0, 0, 255),
			}),
			HatColor = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(0, 0, 0, 255),
				'EditableColor2', RGBA(0, 0, 0, 255),
				'EditableColor3', RGBA(0, 0, 0, 255),
			}),
			Head = "Head_Hitman",
			HeadColor = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(0, 0, 0, 255),
				'EditableColor2', RGBA(0, 0, 0, 255),
				'EditableColor3', RGBA(0, 0, 0, 255),
			}),
			HipColor = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(0, 0, 0, 255),
				'EditableColor2', RGBA(0, 0, 0, 255),
				'EditableColor3', RGBA(0, 0, 0, 255),
			}),
			Pants = "EquipmentIMPGunny_Pants",
			PantsColor = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(30, 20, 5, 255),
				'EditableColor2', RGBA(10, 10, 10, 255),
				'EditableColor3', RGBA(30, 15, 10, 255),
			}),
			ShirtColor = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(0, 0, 0, 255),
				'EditableColor2', RGBA(0, 0, 0, 255),
				'EditableColor3', RGBA(0, 0, 0, 255),
			}),
			group = "Mercs",
			id = "Hitman_battlemode",
		}),
		PlaceObj('ModItemAppearancePreset', {
			Armor = "",
			ArmorColor = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(100, 114, 118, 255),
				'EditableColor2', RGBA(38, 4, 4, 255),
				'EditableColor3', RGBA(88, 92, 68, 255),
			}),
			Body = "EquipmentBiff_Top",
			BodyColor = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(36, 18, 10, 255),
				'EditableColor2', RGBA(27, 27, 28, 255),
				'EditableColor3', RGBA(51, 53, 43, 255),
			}),
			ChestColor = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(0, 0, 0, 255),
				'EditableColor2', RGBA(0, 0, 0, 255),
				'EditableColor3', RGBA(0, 0, 0, 255),
			}),
			Hair = "EquipmentIce_Hair",
			HairColor = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(26, 26, 26, 255),
				'EditableRoughness1', 55,
				'EditableColor2', RGBA(19, 19, 19, 255),
				'EditableMetallic2', -128,
				'EditableRoughness3', 62,
				'EditableMetallic3', 127,
			}),
			HairParam2 = 20,
			Hat2Color = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(0, 0, 0, 255),
				'EditableColor2', RGBA(0, 0, 0, 255),
				'EditableColor3', RGBA(0, 0, 0, 255),
			}),
			HatColor = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(0, 0, 0, 255),
				'EditableColor2', RGBA(0, 0, 0, 255),
				'EditableColor3', RGBA(0, 0, 0, 255),
			}),
			Head = "Head_Ice",
			HeadColor = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(0, 0, 0, 255),
				'EditableColor2', RGBA(0, 0, 0, 255),
				'EditableColor3', RGBA(0, 0, 0, 255),
			}),
			HipColor = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(0, 0, 0, 255),
				'EditableColor2', RGBA(0, 0, 0, 255),
				'EditableColor3', RGBA(0, 0, 0, 255),
			}),
			Pants = "EquipmentIce_Bottom",
			PantsColor = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(0, 0, 0, 255),
				'EditableColor2', RGBA(0, 0, 0, 255),
				'EditableColor3', RGBA(0, 0, 0, 255),
			}),
			Shirt = "",
			ShirtColor = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(189, 171, 149, 255),
				'EditableColor2', RGBA(0, 0, 0, 255),
				'EditableColor3', RGBA(0, 0, 0, 255),
			}),
			group = "Mercs",
			id = "Ice_battlemode",
		}),
		PlaceObj('ModItemAppearancePreset', {
			Armor = "",
			ArmorColor = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(33, 19, 4, 255),
				'EditableColor2', RGBA(0, 0, 0, 255),
				'EditableColor3', RGBA(0, 0, 0, 255),
			}),
			Body = "Faction_Adonis_Top_03",
			BodyColor = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(50, 29, 25, 255),
				'EditableColor2', RGBA(72, 58, 34, 255),
				'EditableColor3', RGBA(20, 15, 8, 255),
			}),
			Chest = "Faction_RadioDevice_01",
			ChestColor = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(27, 21, 21, 255),
				'EditableColor2', RGBA(27, 21, 21, 255),
				'EditableColor3', RGBA(27, 21, 21, 255),
			}),
			Hair = "",
			HairColor = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(0, 0, 0, 255),
				'EditableColor2', RGBA(0, 0, 0, 255),
			}),
			Hat = "EquipmentIvan_Hat",
			Hat2Color = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(0, 0, 0, 255),
				'EditableColor2', RGBA(0, 0, 0, 255),
				'EditableColor3', RGBA(0, 0, 0, 255),
			}),
			HatColor = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(0, 0, 0, 255),
				'EditableColor2', RGBA(0, 0, 0, 255),
				'EditableColor3', RGBA(0, 0, 0, 255),
			}),
			Head = "Head_Ivan",
			HeadColor = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(0, 0, 0, 255),
				'EditableColor2', RGBA(0, 0, 0, 255),
				'EditableColor3', RGBA(0, 0, 0, 255),
			}),
			Hip = "Faction_Acc_Heavy",
			HipColor = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(9, 7, 4, 255),
				'EditableColor2', RGBA(10, 9, 8, 255),
				'EditableColor3', RGBA(0, 0, 0, 255),
			}),
			Pants = "EquipmentIvan_Bottom",
			PantsColor = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(42, 21, 4, 255),
				'EditableColor2', RGBA(72, 41, 7, 255),
				'EditableColor3', RGBA(168, 146, 110, 255),
			}),
			Shirt = "Faction_Gloves_01",
			ShirtColor = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(17, 14, 9, 255),
				'EditableColor2', RGBA(0, 0, 0, 255),
				'EditableColor3', RGBA(0, 0, 0, 255),
			}),
			group = "Default",
			id = "Ivan_battlemode",
		}),
		PlaceObj('ModItemAppearancePreset', {
			Armor = "",
			ArmorColor = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(11, 16, 8, 255),
				'EditableRoughness1', 127,
				'EditableColor2', RGBA(3, 3, 3, 255),
				'EditableColor3', RGBA(0, 0, 0, 255),
			}),
			Body = "NPCCostumeFemale_Shirt_04",
			BodyColor = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(79, 33, 17, 255),
				'EditableColor2', RGBA(11, 13, 6, 255),
				'EditableColor3', RGBA(0, 0, 0, 255),
			}),
			ChestColor = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(0, 0, 0, 255),
				'EditableColor2', RGBA(0, 0, 0, 255),
				'EditableColor3', RGBA(0, 0, 0, 255),
			}),
			Hair = "EquipmentKalyna_Hair",
			HairColor = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(103, 34, 10, 255),
				'EditableRoughness1', 12,
				'EditableMetallic1', -128,
				'EditableColor2', RGBA(42, 14, 7, 255),
				'EditableRoughness2', -66,
				'EditableMetallic2', -128,
				'EditableMetallic3', 127,
			}),
			HairParam1 = 69,
			Hat = "",
			Hat2Color = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(0, 0, 0, 255),
				'EditableColor2', RGBA(0, 0, 0, 255),
				'EditableColor3', RGBA(0, 0, 0, 255),
			}),
			HatColor = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(0, 0, 0, 255),
				'EditableColor2', RGBA(0, 0, 0, 255),
				'EditableColor3', RGBA(0, 0, 0, 255),
			}),
			Head = "Head_Kalyna",
			HeadColor = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(0, 0, 0, 255),
				'EditableColor2', RGBA(0, 0, 0, 255),
				'EditableColor3', RGBA(0, 0, 0, 255),
			}),
			HipColor = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(0, 0, 0, 255),
				'EditableColor2', RGBA(0, 0, 0, 255),
				'EditableColor3', RGBA(0, 0, 0, 255),
			}),
			Pants = "EquipmentFemale_Pants_02",
			PantsColor = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(16, 19, 9, 255),
				'EditableColor2', RGBA(25, 21, 16, 255),
				'EditableColor3', RGBA(3, 3, 3, 255),
				'EditableRoughness3', 21,
			}),
			Shirt = "",
			ShirtColor = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(177, 22, 14, 255),
				'EditableColor2', RGBA(0, 0, 0, 255),
				'EditableColor3', RGBA(0, 0, 0, 255),
			}),
			group = "Default",
			id = "Kalyna_battlemode",
		}),
		PlaceObj('ModItemAppearancePreset', {
			ArmorColor = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(0, 0, 0, 255),
				'EditableColor2', RGBA(0, 0, 0, 255),
				'EditableColor3', RGBA(0, 0, 0, 255),
			}),
			Body = "Faction_GrandChien_Top_12",
			BodyColor = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(18, 9, 5, 255),
				'EditableColor2', RGBA(130, 128, 120, 255),
				'EditableColor3', RGBA(196, 175, 117, 255),
			}),
			Chest = "",
			ChestColor = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(0, 0, 0, 255),
				'EditableColor2', RGBA(0, 0, 0, 255),
				'EditableColor3', RGBA(0, 0, 0, 255),
			}),
			Hair = "EquipmentMagic_Hair",
			HairColor = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(1, 0, 0, 255),
				'EditableRoughness1', 29,
				'EditableMetallic1', 4,
				'EditableColor2', RGBA(23, 19, 18, 255),
			}),
			HairParam2 = 32,
			HairParam3 = 83,
			Hat = "EquipmentMagic_Hat",
			Hat2Color = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(0, 0, 0, 255),
				'EditableColor2', RGBA(0, 0, 0, 255),
				'EditableColor3', RGBA(0, 0, 0, 255),
			}),
			HatColor = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(0, 0, 0, 255),
				'EditableColor2', RGBA(0, 0, 0, 255),
				'EditableColor3', RGBA(0, 0, 0, 255),
			}),
			Head = "Head_Magic",
			HeadColor = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(0, 0, 0, 255),
				'EditableColor2', RGBA(0, 0, 0, 255),
				'EditableColor3', RGBA(0, 0, 0, 255),
			}),
			Hip = "Faction_Acc_Recon",
			HipColor = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(20, 20, 20, 255),
				'EditableColor2', RGBA(189, 171, 149, 255),
				'EditableColor3', RGBA(230, 222, 202, 255),
			}),
			Pants = "Faction_GrandChien_Bottom_04",
			PantsColor = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(130, 128, 120, 255),
				'EditableColor2', RGBA(48, 25, 14, 255),
				'EditableColor3', RGBA(11, 11, 11, 255),
			}),
			ShirtColor = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(0, 0, 0, 255),
				'EditableColor2', RGBA(0, 0, 0, 255),
				'EditableColor3', RGBA(0, 0, 0, 255),
			}),
			group = "Default",
			id = "Magic_battlemode",
		}),
		PlaceObj('ModItemAppearancePreset', {
			ArmorColor = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(0, 0, 0, 255),
				'EditableColor2', RGBA(0, 0, 0, 255),
				'EditableColor3', RGBA(0, 0, 0, 255),
			}),
			Body = "EquipmentMD_Top",
			BodyColor = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(0, 0, 0, 255),
				'EditableColor2', RGBA(0, 0, 0, 255),
				'EditableColor3', RGBA(67, 30, 12, 255),
			}),
			ChestColor = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(0, 0, 0, 255),
				'EditableColor2', RGBA(0, 0, 0, 255),
				'EditableColor3', RGBA(0, 0, 0, 255),
			}),
			Hair = "EquipmentMD_Hair",
			HairColor = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(17, 17, 17, 255),
				'EditableColor2', RGBA(41, 41, 41, 255),
				'EditableRoughness2', -15,
				'EditableMetallic2', -128,
				'EditableRoughness3', -128,
				'EditableMetallic3', 127,
			}),
			HairParam2 = 11,
			HairParam3 = 110,
			Hat2 = "",
			Hat2Color = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(0, 0, 0, 255),
				'EditableColor2', RGBA(0, 0, 0, 255),
				'EditableColor3', RGBA(0, 0, 0, 255),
			}),
			HatColor = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(0, 0, 0, 255),
				'EditableColor2', RGBA(0, 0, 0, 255),
				'EditableColor3', RGBA(0, 0, 0, 255),
			}),
			Head = "Head_MD",
			HeadColor = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(0, 0, 0, 255),
				'EditableColor2', RGBA(0, 0, 0, 255),
				'EditableColor3', RGBA(0, 0, 0, 255),
			}),
			Hip = "",
			HipColor = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(0, 0, 0, 255),
				'EditableColor2', RGBA(0, 0, 0, 255),
				'EditableColor3', RGBA(0, 0, 0, 255),
			}),
			Pants = "EquipmentIMPGunny_Pants",
			PantsColor = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(30, 30, 20, 255),
				'EditableColor2', RGBA(3, 3, 3, 255),
				'EditableColor3', RGBA(17, 17, 17, 255),
			}),
			ShirtColor = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(0, 0, 0, 255),
				'EditableColor2', RGBA(0, 0, 0, 255),
				'EditableColor3', RGBA(0, 0, 0, 255),
			}),
			group = "Mercs",
			id = "MD_battlemode",
		}),
		PlaceObj('ModItemAppearancePreset', {
			Armor = "EquipmentFemale_FlackVest",
			ArmorColor = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(25, 25, 25, 255),
				'EditableColor2', RGBA(25, 25, 25, 255),
				'EditableColor3', RGBA(10, 32, 6, 255),
			}),
			Body = "EquipmentMeltdown_Top",
			BodyColor = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(0, 0, 0, 255),
				'EditableColor2', RGBA(0, 0, 0, 255),
				'EditableColor3', RGBA(0, 0, 0, 255),
			}),
			ChestColor = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(0, 0, 0, 255),
				'EditableColor2', RGBA(0, 0, 0, 255),
				'EditableColor3', RGBA(0, 0, 0, 255),
			}),
			Hair = "EquipmentMeltdown_Hair",
			HairColor = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(8, 7, 6, 255),
				'EditableColor2', RGBA(49, 36, 13, 255),
				'EditableMetallic2', -128,
				'EditableRoughness3', -128,
			}),
			HairParam2 = 29,
			HairParam3 = 117,
			Hat2 = "",
			Hat2Color = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(0, 0, 0, 255),
				'EditableColor2', RGBA(0, 0, 0, 255),
				'EditableColor3', RGBA(0, 0, 0, 255),
			}),
			HatColor = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(0, 0, 0, 255),
				'EditableColor2', RGBA(0, 0, 0, 255),
				'EditableColor3', RGBA(0, 0, 0, 255),
			}),
			Head = "Head_Meltdown",
			HeadColor = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(0, 0, 0, 255),
				'EditableColor2', RGBA(0, 0, 0, 255),
				'EditableColor3', RGBA(0, 0, 0, 255),
			}),
			HipColor = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(0, 0, 0, 255),
				'EditableColor2', RGBA(0, 0, 0, 255),
				'EditableColor3', RGBA(0, 0, 0, 255),
			}),
			Pants = "EquipmentScope_Bottom",
			PantsColor = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(0, 0, 0, 255),
				'EditableColor2', RGBA(0, 0, 0, 255),
				'EditableColor3', RGBA(0, 0, 0, 255),
			}),
			Shirt = "",
			ShirtColor = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(0, 0, 0, 255),
				'EditableColor2', RGBA(0, 0, 0, 255),
				'EditableColor3', RGBA(0, 0, 0, 255),
			}),
			group = "Mercs",
			id = "Meltdown_battlemode",
		}),
		PlaceObj('ModItemAppearancePreset', {
			Armor = "EquipmentFemale_InterceptorVest_02",
			ArmorColor = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(4, 4, 4, 255),
				'EditableColor2', RGBA(17, 17, 17, 255),
				'EditableColor3', RGBA(10, 8, 8, 255),
			}),
			Body = "Female_Body_01",
			BodyColor = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(87, 37, 20, 255),
				'EditableColor2', RGBA(9, 9, 9, 255),
				'EditableRoughness2', 127,
				'EditableMetallic2', 4,
				'EditableColor3', RGBA(9, 9, 9, 255),
				'EditableRoughness3', 127,
			}),
			ChestColor = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(0, 0, 0, 255),
				'EditableColor2', RGBA(0, 0, 0, 255),
				'EditableColor3', RGBA(0, 0, 0, 255),
			}),
			Hair = "EquipmentMeltdown_Hair",
			HairColor = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(213, 169, 65, 255),
				'EditableRoughness1', 88,
				'EditableMetallic1', -128,
				'EditableColor2', RGBA(152, 108, 65, 255),
				'EditableMetallic2', -128,
				'EditableMetallic3', 127,
			}),
			HairParam3 = 178,
			Hat = "",
			Hat2 = "",
			Hat2Color = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(0, 0, 0, 255),
				'EditableColor2', RGBA(0, 0, 0, 255),
				'EditableColor3', RGBA(0, 0, 0, 255),
			}),
			HatColor = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(0, 0, 0, 255),
				'EditableColor2', RGBA(0, 0, 0, 255),
				'EditableColor3', RGBA(0, 0, 0, 255),
			}),
			Head = "Head_Mouse",
			HeadColor = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(0, 0, 0, 255),
				'EditableColor2', RGBA(0, 0, 0, 255),
				'EditableColor3', RGBA(0, 0, 0, 255),
			}),
			HipColor = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(0, 0, 0, 255),
				'EditableColor2', RGBA(0, 0, 0, 255),
				'EditableColor3', RGBA(0, 0, 0, 255),
			}),
			Pants = "EquipmentScope_Bottom",
			PantsColor = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(150, 61, 61, 255),
				'EditableColor2', RGBA(167, 62, 62, 255),
				'EditableColor3', RGBA(139, 71, 71, 255),
			}),
			Shirt = "EquipmentFemale_Shirt_01",
			ShirtColor = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(6, 6, 6, 255),
				'EditableRoughness1', -128,
				'EditableColor2', RGBA(17, 17, 17, 255),
				'EditableColor3', RGBA(17, 17, 17, 255),
			}),
			group = "Default",
			id = "Mouse_battlemode",
		}),
		PlaceObj('ModItemAppearancePreset', {
			Armor = "",
			ArmorColor = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(0, 0, 0, 255),
				'EditableColor2', RGBA(0, 0, 0, 255),
				'EditableColor3', RGBA(0, 0, 0, 255),
			}),
			Body = "Faction_Rebels_Top_Stormer",
			BodyColor = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(104, 48, 21, 255),
				'EditableColor2', RGBA(20, 22, 12, 255),
				'EditableColor3', RGBA(58, 53, 39, 255),
			}),
			Chest = "",
			ChestColor = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(0, 0, 0, 255),
				'EditableColor2', RGBA(0, 0, 0, 255),
				'EditableColor3', RGBA(0, 0, 0, 255),
			}),
			Hair = "EquipmentNails_Hair",
			HairColor = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(60, 25, 25, 255),
				'EditableColor2', RGBA(45, 38, 38, 255),
				'EditableRoughness2', -78,
				'EditableMetallic2', -128,
				'EditableRoughness3', -73,
			}),
			HairParam2 = 14,
			HairParam3 = 65,
			Hat = "EquipmentNails_Headband",
			Hat2Color = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(0, 0, 0, 255),
				'EditableColor2', RGBA(0, 0, 0, 255),
				'EditableColor3', RGBA(0, 0, 0, 255),
			}),
			HatColor = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(0, 0, 0, 255),
				'EditableColor2', RGBA(0, 0, 0, 255),
				'EditableColor3', RGBA(0, 0, 0, 255),
			}),
			Head = "Head_Nails",
			HeadColor = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(0, 0, 0, 255),
				'EditableColor2', RGBA(0, 0, 0, 255),
				'EditableColor3', RGBA(0, 0, 0, 255),
			}),
			Hip = "Faction_Acc_Recon",
			HipColor = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(5, 5, 5, 255),
				'EditableColor2', RGBA(60, 44, 44, 255),
				'EditableColor3', RGBA(78, 47, 47, 255),
			}),
			Pants = "Faction_GrandChien_Bottom_03",
			PantsColor = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(19, 24, 7, 255),
				'EditableColor2', RGBA(18, 18, 18, 255),
				'EditableColor3', RGBA(27, 26, 26, 255),
			}),
			Shirt = "Faction_Gloves_01",
			ShirtColor = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(16, 16, 16, 255),
				'EditableColor2', RGBA(12, 12, 12, 255),
				'EditableColor3', RGBA(11, 11, 11, 255),
			}),
			group = "Default",
			id = "Nails_battlemode",
		}),
		PlaceObj('ModItemAppearancePreset', {
			Armor = "",
			ArmorColor = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(0, 0, 0, 255),
				'EditableColor2', RGBA(0, 0, 0, 255),
				'EditableColor3', RGBA(0, 0, 0, 255),
			}),
			Body = "Faction_GrandChien_Top_11",
			BodyColor = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(200, 120, 75, 255),
				'EditableColor2', RGBA(17, 17, 17, 255),
				'EditableColor3', RGBA(17, 17, 17, 255),
			}),
			Chest = "Faction_RadioDevice_01",
			ChestColor = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(5, 5, 5, 255),
				'EditableColor2', RGBA(5, 5, 5, 255),
				'EditableColor3', RGBA(5, 5, 5, 255),
			}),
			Hair = "EquipmentReaper_Hair",
			HairColor = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(61, 26, 12, 255),
				'EditableColor2', RGBA(133, 61, 35, 255),
				'EditableMetallic2', -128,
				'EditableColor3', RGBA(0, 0, 0, 255),
				'EditableMetallic3', 127,
			}),
			HairParam2 = 25,
			HairParam3 = 215,
			Hat2Color = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(0, 0, 0, 255),
				'EditableColor2', RGBA(0, 0, 0, 255),
				'EditableColor3', RGBA(0, 0, 0, 255),
			}),
			HatColor = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(0, 0, 0, 255),
				'EditableColor2', RGBA(0, 0, 0, 255),
				'EditableColor3', RGBA(0, 0, 0, 255),
			}),
			Head = "Head_Reaper",
			HeadColor = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(0, 0, 0, 255),
				'EditableColor2', RGBA(0, 0, 0, 255),
				'EditableColor3', RGBA(0, 0, 0, 255),
			}),
			Hip = "Faction_Acc_Marksman",
			HipColor = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(10, 10, 10, 255),
				'EditableColor2', RGBA(75, 5, 2, 255),
				'EditableColor3', RGBA(0, 0, 0, 255),
			}),
			Pants = "Faction_GrandChien_Bottom_03",
			PantsColor = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(17, 17, 17, 255),
				'EditableColor2', RGBA(17, 17, 17, 255),
				'EditableColor3', RGBA(200, 15, 5, 255),
			}),
			Shirt = "Faction_Gloves_01",
			ShirtColor = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(17, 17, 17, 255),
				'EditableColor2', RGBA(17, 17, 17, 255),
				'EditableColor3', RGBA(200, 15, 5, 255),
			}),
			group = "Mercs",
			id = "Reaper_battlemode",
		}),
		PlaceObj('ModItemAppearancePreset', {
			Armor = "",
			ArmorColor = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(60, 38, 8, 255),
				'EditableColor2', RGBA(22, 66, 8, 255),
				'EditableColor3', RGBA(124, 130, 96, 255),
			}),
			Body = "Faction_GrandChien_Top_12",
			BodyColor = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(200, 120, 60, 255),
				'EditableColor2', RGBA(8, 36, 2, 255),
				'EditableColor3', RGBA(50, 75, 50, 255),
			}),
			ChestColor = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(0, 0, 0, 255),
				'EditableColor2', RGBA(0, 0, 0, 255),
				'EditableColor3', RGBA(0, 0, 0, 255),
			}),
			Hair = "EquipmentSidney_Hair",
			HairColor = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(98, 83, 74, 255),
				'EditableRoughness1', 48,
				'EditableColor2', RGBA(57, 34, 16, 255),
				'EditableMetallic2', -128,
				'EditableColor3', RGBA(0, 0, 0, 255),
				'EditableRoughness3', -25,
				'EditableMetallic3', 127,
			}),
			HairParam2 = 16,
			HairParam3 = 78,
			Hat2Color = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(0, 0, 0, 255),
				'EditableColor2', RGBA(0, 0, 0, 255),
				'EditableColor3', RGBA(0, 0, 0, 255),
			}),
			HatColor = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(0, 0, 0, 255),
				'EditableColor2', RGBA(0, 0, 0, 255),
				'EditableColor3', RGBA(0, 0, 0, 255),
			}),
			Head = "Head_Sidney",
			HeadColor = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(0, 0, 0, 255),
				'EditableColor2', RGBA(0, 0, 0, 255),
				'EditableColor3', RGBA(0, 0, 0, 255),
			}),
			Hip = "Faction_Acc_Soldier",
			HipColor = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(2, 9, 0, 255),
				'EditableColor2', RGBA(5, 5, 5, 255),
				'EditableColor3', RGBA(5, 5, 5, 255),
			}),
			Pants = "EquipmentIMPGunny_Pants",
			PantsColor = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(1, 5, 0, 255),
				'EditableColor2', RGBA(5, 5, 5, 255),
				'EditableColor3', RGBA(5, 5, 5, 255),
			}),
			Shirt = "Faction_Gloves_01",
			ShirtColor = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(5, 5, 5, 255),
				'EditableColor2', RGBA(5, 5, 5, 255),
				'EditableColor3', RGBA(6, 24, 1, 255),
			}),
			group = "Mercs",
			id = "Sidney_battlemode",
		}),
		PlaceObj('ModItemAppearancePreset', {
			Armor = "",
			ArmorColor = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(22, 66, 8, 255),
				'EditableColor2', RGBA(0, 0, 0, 255),
				'EditableColor3', RGBA(88, 92, 68, 255),
			}),
			Body = "EquipmentBiff_Top",
			BodyColor = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(203, 101, 41, 255),
				'EditableColor2', RGBA(109, 69, 17, 255),
				'EditableColor3', RGBA(17, 17, 17, 255),
			}),
			Chest = "",
			ChestColor = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(17, 17, 17, 255),
				'EditableColor2', RGBA(27, 17, 4, 255),
				'EditableColor3', RGBA(124, 130, 96, 255),
			}),
			Hair = "EquipmentScully_Hair",
			HairColor = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(236, 154, 89, 255),
				'EditableRoughness1', -6,
				'EditableColor2', RGBA(171, 112, 50, 255),
				'EditableRoughness2', -42,
				'EditableMetallic2', -128,
				'EditableColor3', RGBA(255, 255, 255, 255),
				'EditableMetallic3', 127,
			}),
			HairParam1 = 219,
			HairParam2 = 44,
			HairParam3 = 127,
			Hat2Color = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(0, 0, 0, 255),
				'EditableColor2', RGBA(0, 0, 0, 255),
				'EditableColor3', RGBA(0, 0, 0, 255),
			}),
			HatColor = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(0, 0, 0, 255),
				'EditableColor2', RGBA(0, 0, 0, 255),
				'EditableColor3', RGBA(0, 0, 0, 255),
			}),
			Head = "Head_Scully",
			HeadColor = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(53, 134, 24, 255),
				'EditableColor2', RGBA(48, 25, 14, 255),
				'EditableColor3', RGBA(88, 92, 68, 255),
			}),
			Hip = "Faction_Acc_Stormer",
			HipColor = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(17, 17, 17, 255),
				'EditableColor2', RGBA(27, 17, 4, 255),
				'EditableColor3', RGBA(17, 17, 17, 255),
			}),
			Pants = "Faction_Adonis_Bottom_Camo_02",
			PantsColor = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(196, 175, 117, 255),
				'EditableColor2', RGBA(17, 17, 17, 255),
				'EditableColor3', RGBA(17, 17, 17, 255),
			}),
			Shirt = "",
			ShirtColor = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(0, 0, 0, 255),
				'EditableColor2', RGBA(0, 0, 0, 255),
				'EditableColor3', RGBA(0, 0, 0, 255),
			}),
			group = "Mercs",
			id = "Scully_battlemode",
		}),
		PlaceObj('ModItemAppearancePreset', {
			ArmorColor = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(0, 0, 0, 255),
				'EditableColor2', RGBA(0, 0, 0, 255),
				'EditableColor3', RGBA(0, 0, 0, 255),
			}),
			Body = "EquipmentIMPGunny_Top",
			BodyColor = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(66, 29, 17, 255),
				'EditableColor2', RGBA(51, 51, 51, 255),
				'EditableColor3', RGBA(177, 22, 14, 255),
			}),
			ChestColor = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(0, 0, 0, 255),
				'EditableColor2', RGBA(0, 0, 0, 255),
				'EditableColor3', RGBA(0, 0, 0, 255),
			}),
			Hair = "",
			HairColor = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(52, 40, 35, 255),
				'EditableColor2', RGBA(24, 20, 16, 255),
				'EditableColor3', RGBA(0, 0, 0, 255),
			}),
			Hat = "EquipmentTex_Hat",
			Hat2Color = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(0, 0, 0, 255),
				'EditableColor2', RGBA(0, 0, 0, 255),
				'EditableColor3', RGBA(0, 0, 0, 255),
			}),
			HatColor = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(0, 0, 0, 255),
				'EditableColor2', RGBA(0, 0, 0, 255),
				'EditableColor3', RGBA(0, 0, 0, 255),
			}),
			Head = "Head_Tex",
			HeadColor = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(0, 0, 0, 255),
				'EditableColor2', RGBA(0, 0, 0, 255),
				'EditableColor3', RGBA(0, 0, 0, 255),
			}),
			HipColor = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(0, 0, 0, 255),
				'EditableColor2', RGBA(0, 0, 0, 255),
				'EditableColor3', RGBA(0, 0, 0, 255),
			}),
			Pants = "EquipmentIMPGunny_Pants",
			PantsColor = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(21, 21, 21, 255),
				'EditableColor2', RGBA(20, 10, 5, 255),
				'EditableColor3', RGBA(20, 10, 5, 255),
			}),
			ShirtColor = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(0, 0, 0, 255),
				'EditableColor2', RGBA(0, 0, 0, 255),
				'EditableColor3', RGBA(0, 0, 0, 255),
			}),
			group = "Mercs",
			id = "Tex_battlemode",
		}),
		PlaceObj('ModItemAppearancePreset', {
			ArmorColor = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(0, 0, 0, 255),
				'EditableColor2', RGBA(0, 0, 0, 255),
				'EditableColor3', RGBA(0, 0, 0, 255),
			}),
			Body = "Faction_Adonis_Top_Camo_04",
			BodyColor = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(63, 33, 17, 255),
				'EditableColor2', RGBA(40, 46, 27, 255),
				'EditableColor3', RGBA(27, 25, 19, 255),
			}),
			Chest = "Faction_Acc_Heavy_02",
			ChestColor = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(5, 4, 3, 255),
				'EditableColor2', RGBA(6, 6, 6, 255),
				'EditableColor3', RGBA(15, 15, 15, 255),
			}),
			Hair = "EquipmentThor_Hair",
			HairColor = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(51, 48, 48, 255),
				'EditableMetallic1', 52,
				'EditableColor2', RGBA(26, 22, 21, 255),
				'EditableMetallic2', -128,
				'EditableColor3', RGBA(0, 0, 0, 255),
				'EditableMetallic3', 127,
			}),
			HairParam1 = 30,
			HairParam2 = 15,
			HairParam3 = 126,
			Hat = "EquipmentThor_Headband",
			Hat2 = "",
			Hat2AttachOffsetX = 23,
			Hat2AttachOffsetY = -3,
			Hat2AttachOffsetZ = -6,
			Hat2Color = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(0, 0, 0, 255),
				'EditableColor2', RGBA(0, 0, 0, 255),
				'EditableColor3', RGBA(0, 0, 0, 255),
			}),
			HatColor = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(0, 0, 0, 255),
				'EditableColor2', RGBA(0, 0, 0, 255),
				'EditableColor3', RGBA(0, 0, 0, 255),
			}),
			Head = "Head_Thor",
			HeadColor = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(0, 0, 0, 255),
				'EditableColor2', RGBA(0, 0, 0, 255),
				'EditableColor3', RGBA(0, 0, 0, 255),
			}),
			Hip = "Faction_Acc_Heavy",
			HipColor = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(5, 4, 3, 255),
				'EditableColor2', RGBA(6, 6, 6, 255),
				'EditableColor3', RGBA(15, 15, 15, 255),
			}),
			Pants = "Faction_Adonis_Bottom_Camo_01",
			PantsColor = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(40, 46, 27, 255),
				'EditableColor2', RGBA(27, 25, 19, 255),
				'EditableColor3', RGBA(27, 25, 19, 255),
			}),
			Shirt = "",
			ShirtColor = PlaceObj('ColorizationPropSet', {
				'EditableColor1', RGBA(0, 0, 0, 255),
				'EditableColor2', RGBA(0, 0, 0, 255),
				'EditableColor3', RGBA(0, 0, 0, 255),
			}),
			group = "Default",
			id = "Thor_battlemode",
		}),
		}),
}